# Generated by Django 4.1.5 on 2023-02-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accountholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Withdraw', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('interestperyear', models.IntegerField()),
            ],
        ),
    ]
