# Generated by Django 4.1.5 on 2023-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_banktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='amounttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw', models.IntegerField()),
            ],
        ),
    ]
